version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  trueshorts:
    image: shubhthecoder/trueshorts_backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./faiss_indexes:/app/faiss_indexes
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - GNEWS_API_KEY=f30e4c031aa2ea070ba8b4fca5109aa3
      - SECRET_KEY=1a2b3c4d5e6f7g8h9i0jkLMNOPQrstuvWXyz9876543210
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - SERPER_API_KEY=0f8f7d962eeb0953e4190e2311e140c5a6c02d50
      - GOOGLE_FACT_CHECK_API_KEY=AIzaSyDLMGxKA8LhHeejl52owJ6kLEYYWEnnnbw
      - GROQ_API_KEY=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

  backend:
    image: shubhthecoder/trueshorts_backend:latest
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongodb_data: 