name: Auto Stop Azure Container on Idle

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  check-idle-and-stop:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pymongo python-dateutil

      - name: Check MongoDB for idle status
        id: check_idle
        run: |
          python <<EOF
          import os
          from datetime import datetime, timedelta
          from pymongo import MongoClient
          from dateutil.parser import parse

          mongo_uri = os.environ["MONGO_URI"]
          client = MongoClient(mongo_uri)
          db = client["activity"]
          doc = db["heartbeat"].find_one({"_id": "trueshorts-backend"})
          client.close()

          if not doc or "last_active" not in doc:
              is_idle = True
          else:
              last_active = parse(str(doc["last_active"]))
              is_idle = (datetime.utcnow() - last_active) > timedelta(hours=1.5)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"idle={str(is_idle).lower()}\n")
          EOF

      - name: Azure Login
        if: steps.check_idle.outputs.idle == 'true'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Azure Container Instance
        if: steps.check_idle.outputs.idle == 'true'
        run: |
          az container stop \
            --name trueshorts-backend \
            --resource-group trueshorts-backend

      - name: Send Email Notification
        if: steps.check_idle.outputs.idle == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_FROM }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🛑 Container Auto-Stopped: trueshorts-backend"
          to: |
            shubham07kumargupta@gmail.com,
            iamnidhinupur@gmail.com,
            ashishguptaaur2020@gmail.com,
            pranavpratyush1003@gmail.com
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Hello Team,

            ✅ The Azure container `trueshorts-backend` was automatically stopped due to 1.5 hours of inactivity.

            ⚙️ Cron job: every 15 minutes  
            ⏱ Last activity check passed idle condition

            Best regards,  
            GitHub Actions – Auto Stop Monitor
