name: CI/CD - Build & Deploy FastAPI on Azure Container Instance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: shubhthecoder/trueshorts_backend:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Azure Container Instance with new image
      run: |
        az container update \
          --name trueshorts-backend \
          --resource-group trueshorts-backend \
          --set containers[0].image=shubhthecoder/trueshorts_backend:latest

    - name: Restart Azure Container Instance
      run: |
        az container restart \
          --name trueshorts-backend \
          --resource-group trueshorts-backend

    - name: Send email notification on successful deploy
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_FROM }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "✅ CI/CD Deployed: trueshorts-backend"
        to: |
          shubham07kumargupta@gmail.com,
          iamnidhinupur@gmail.com,
          ashishguptaaur2020@gmail.com,
          pranavpratyush1003@gmail.com
        from: ${{ secrets.EMAIL_FROM }}
        body: |
          Hello Team,

          The latest FastAPI backend for TrueShorts has been successfully deployed on Azure Container Instance 🚀

          ✅ Image: shubhthecoder/trueshorts_backend:latest  
          ✅ Container: trueshorts-backend  
          🌐 URL: https://trueshorts-api.duejcqajdff7c5h2.centralindia.azurecontainer.io

          Regards,  
          GitHub Actions
